name: pub_version_plus
description: Easily increment version numbers in pubspec.yaml files with a single command.
repository: https://github.com/mrgnhnt96/pub_version_plus
version: 1.1.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  path: ^1.8.3
  pubspec_parse: ^1.2.1
  pub_semver: ^2.1.3
  args: ^2.3.2
  io: ^1.0.4
  meta: ^1.9.0

dev_dependencies:
  test: ^1.17.12

scripts: derry.yaml

executables:
  pubversion: main