name: pub_version_plus
description: Easily increment version numbers in pubspec.yaml files with a single command.
repository: https://github.com/mrgnhnt96/pub_version_plus
version: 3.1.1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  path: ^1.9.0
  pubspec_parse: ^1.2.3
  pub_semver: ^2.1.4
  args: ^2.5.0
  io: ^1.0.4
  meta: ^1.14.0
  file: ^7.0.0

dev_dependencies:
  test: ^1.25.4

executables:
  pubversion: main